[package]
name = "bevygame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"
bevy-inspector-egui = "0.13.0"
bevy_asset_loader = "0.12.1"
bevy_ecs_tilemap = "0.8.0"
